# Generated by Django 3.1.6 on 2021-02-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsecuro', '0002_cameras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameras',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='addresses',
            name='coordinates',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
