# Generated by Django 3.1.6 on 2021-02-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camsecuro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('uuid', models.CharField(max_length=200)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camsecuro.addresses')),
            ],
        ),
    ]
